### ISSUE TITLE
Default config not setting `runtime_root`

### ISSUE THREAD

**Issue by lbogdan** [cri-o/packaging#104]
This is not necessarily a bug, but a small nuisance I ran into while doing some troubleshooting. 

The [default config](https://github.com/cri-o/packaging/blob/4d1edfda6ca11b4a59474cb9e8cc65ff46197055/templates/latest/cri-o/bundle/10-crio.conf) makes `crun` the default runtime. As `runtime_root` is not set explicitly, and its [default value](https://github.com/cri-o/cri-o/blob/09a65899ab123ec07f1f97cb1154f2be6518afce/pkg/config/config_linux.go#L19
) is `/run/runc`

```golang
// Defaults if none are specified
const (
	defaultRuntime       = "runc"
	DefaultRuntimeType   = "oci"
	DefaultRuntimeRoot   = "/run/runc"
// [...]
```
`crun` ends up writing its state to `/run/runc`, which is at least a bit confusing.

Example from a node running `cri-o` with the default config:

```sh
sudo stat /run/crun
# output:
# stat: cannot statx '/run/crun': No such file or directory

sudo stat /run/runc
#   File: /run/runc
#   Size: 360             Blocks: 0          IO Block: 4096   directory
# Device: 1ah/26d Inode: 1627        Links: 18
# Access: (0700/drwx------)  Uid: (    0/    root)   Gid: (    0/    root)
# [...]

sudo crio-runc list
# load container .cache: container does not exist
# load container 2e73909d020a34a6821b9556b196debb79304379196ad2207f8a7318cdd132bf: container does not exist
# [...]

sudo crio-crun --root=/run/runc list
# NAME                                                             PID       STATUS   BUNDLE PATH                             CREATED                        OWNER
# 765721acc775fa8b84917c5b7eb82b362df2dbf096d71a1e52d66f288788b2c5 1469      running  /run/containers/storage/overlay-containers/765721acc775fa8b84917c5b7eb82b362df2dbf096d71a1e52d66f288788b2c5/userdata 2024-05-05T10:06:58.275462Z    root
[...]
```

To make this less confusing, I suggest explicitly setting `runtime_root` in the default config, for both runtimes:

```diff
--- 10-crio.conf        2024-05-16 12:53:31.793680868 +0000
+++ 10-crio-fixed.conf  2024-05-16 12:54:00.610237735 +0000
@@ -6,6 +6,7 @@

 [crio.runtime.runtimes.crun]
 runtime_path = "/usr/bin/crio-crun"
+runtime_root = "/run/crun"
 monitor_path = "/usr/bin/crio-conmon"
 allowed_annotations = [
     "io.containers.trace-syscall",
@@ -13,4 +14,5 @@

 [crio.runtime.runtimes.runc]
 runtime_path = "/usr/bin/crio-runc"
+runtime_root = "/run/runc"
 monitor_path = "/usr/bin/crio-conmon"
 ```
 
 If you're OK with this approach, I can open a PR.

**Comment by lbogdan** [comment]
As an aside, I was curious what was reason behind the decision to make `crun` the default runtime? AFAIR the OBS packages used `runc` as the default.

**Comment by saschagrunert** [comment]
@lbogdan at some point we decided to use crun for the bundles as default and the packages inherited this decision. :)
