### ISSUE TITLE
Missing CONTRIBUTING.md

### ISSUE THREAD

**Issue by lbogdan** [cri-o/packaging#106]
The DCO check "Details" link

![image](https://github.com/cri-o/packaging/assets/2083930/7413ccca-e6d6-46d4-a1dd-00563cef741e)

and the "contributing" link inside the `openshift-ci` comment when pushing non-signed-
off commits point to a missing `https://github.com/cri-o/packaging/blob/master/CONTRIBUTING.md`.

**Comment by saschagrunert** [comment]
Makes sense, I added on in https://github.com/cri-o/packaging/pull/107
