### ISSUE TITLE
Use CentOS instead of Fedora?

### ISSUE THREAD

**Issue by afbjorklund** [cri-o/packaging#18]
Currently test is using Ubuntu LTS, rather than Ubuntu.

Shouldn't it also use CentOS Stream, rather than Fedora?

---

~~Will make a PR to use Lima, instead of Vagrant. (optionally)~~

~~In part due to https://github.com/hashicorp/vagrant/commit/731e9cb6c48df71d8c3f8d2b929dd35875250d2d (~~Open Source~~)~~

**Comment by saschagrunert** [comment]
Thank you for the report @afbjorklund! Yeah the selection of distributions was more an initial thought from the top of my head. 

Would it make sense to add CentOS side by side to Fedora?

**Comment by afbjorklund** [comment]
One RPM distribution is probably plenty, just wondered you picked the fast moving distribution (since it will go EOL soon)

**Comment by saschagrunert** [comment]
The libvirt link points to a 404: https://cloud.centos.org/centos/9-stream/x86_64/images/CentOS-Stream-Vagrant-9-20230727.1.x86_64.vagrant-libvirt.box

**Comment by afbjorklund** [comment]
Should be newer minor versions available, I think.

Unfortunately we can't use CentOS anymore, only Stream

**Comment by afbjorklund** [comment]
These links might work better:

https://cloud.centos.org/centos/9-stream/x86_64/images/CentOS-Stream-Vagrant-9-latest.x86_64.vagrant-libvirt.box

https://cloud.centos.org/centos/9-stream/x86_64/images/CentOS-Stream-Vagrant-9-latest.x86_64.vagrant-virtualbox.box


Goes in [`config.vm.box_url`](https://developer.hashicorp.com/vagrant/docs/vagrantfile/machine_settings#config-vm-box_url)

**Comment by afbjorklund** [comment]
@saschagrunert : It seems that GHA was already using AlmaLinux 9.2, instead of CentOS Stream 9...

Maybe that would have been a better match ("CentOS LTS"), also for the Vagrant and Lima test jobs?

https://app.vagrantup.com/almalinux/boxes/9

Anyway, synched lima.yaml to match Vagrantfile

**Comment by saschagrunert** [comment]
@afbjorklund I'm not sure, having both distributions somehow tested seems fine to me, even if we have different test scenarios.

**Comment by hasan4791** [comment]
I always use fedora 38 and install all the deps from dnf. Always works sweet.
