### ISSUE TITLE
main instructions don't cover dual IP stack

### ISSUE THREAD

**Issue by performantdata** [cri-o/packaging#199]
Following the instructions at https://github.com/cri-o/packaging/blob/main/README.md#distributions-using-deb-packages works for an IPv4-only configuration, but isn't the best for dual-stack, according to [the more general configuration instructions](https://github.com/cri-o/cri-o/blob/main/contrib/cni/README.md#configuration-directory). Reference to those instructions should be made, like as found at https://github.com/cri-o/cri-o/blob/main/install.md#setup-cni-networking, so that dual-stack users get the correct setup.

Specifically, the `deb` package includes `/etc/cni/net/11-crio-ipv4-bridge.conflist`, but not `10-crio-bridge.conflist`. It might be nice to include the latter into `/etc/cni/net/`, perhaps in some disabled state, non-included file name, etc.

**Comment by performantdata** [comment]
It also seems like the documentation would benefit from pointing out that these particular subnets (10.85.0.0/16, 1100:200::/24) are being used on the CNI bridge, to prevent conflict with CIDRs being used in the host or cluster spaces. (I guess no one should be using 1100:200::/24.)

**Comment by saschagrunert** [comment]
Hey, we switched to the dual stack config 2 weeks ago in https://github.com/cri-o/packaging/pull/197. The next set of patches should have them or you use one of the pre release streams, which require the fix from  https://github.com/cri-o/packaging/pull/198

**Comment by saschagrunert** [comment]
@performantdata the latest prerelease streams should have the dualstack change now.
