### ISSUE TITLE
Packages are incompatible with `podman`

### ISSUE THREAD

**Issue by saschagrunert** [cri-o/packaging#3]
It does not work to install `podman` together with `crio` for `deb` as well as `rpm` packages because they share some configuration files. This should be fixed.

For example:

```
> sed -i 's;apt-get install -y cri-o;apt-get install -y cri-o podman;g' test/ubuntu/Dockerfile
> podman build -f test/ubuntu/Dockerfile
…
Unpacking cri-o (1.29.0~dev-26.1) ...
dpkg: error processing archive /tmp/apt-dpkg-install-iZP7z0/37-cri-o_1.29.0~dev-26.1_amd64.deb (--unpack):
 trying to overwrite '/etc/containers/policy.json', which is also in package golang-github-containers-common 0.44.4+ds1-1
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
…
Errors were encountered while processing:
 /tmp/apt-dpkg-install-iZP7z0/37-cri-o_1.29.0~dev-26.1_amd64.deb
```

**Comment by saschagrunert** [comment]
Fixed with https://github.com/kubernetes/release/pull/3283

**Comment by afbjorklund** [comment]
@saschagrunert : there is still one conflict remaining, with `golang-github-containers-image`

It bundles an empty `/etc/containers/registries.conf` file, consisting only of comments (`#`)

**Comment by saschagrunert** [comment]
> @saschagrunert : there is still one conflict remaining, with `golang-github-containers-image`
> 
> It bundles an empty `/etc/containers/registries.conf` file, consisting only of comments (`#`)
> 
> Maybe the cri-o file can be moved to /etc/containers/registries.conf.d ? Using some file name like crio.conf or such
> 
> That is how the /etc/containers/registries.conf.d/shortnames.conf from golang-github-containers-common works

Yes sure, working on it in https://github.com/cri-o/packaging/pull/17
