### ISSUE TITLE
Add the Kubernetes and CRI-O repository not work on Ubuntu 20

### ISSUE THREAD

**Issue by alanpeng** [cri-o/packaging#35]
W: GPG error: https://prod-cdn.packages.k8s.io/repositories/isv:/kubernetes:/addons:/cri-o:/stable:/v1.28/deb  InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 234654DA9A296436
E: The repository 'https://pkgs.k8s.io/addons:/cri-o:/stable:/v1.28/deb  InRelease' is not signed.

![image](https://github.com/cri-o/packaging/assets/3273357/73336a7d-0d41-4490-92ae-871c334f94ea)

**Comment by alanpeng** [comment]
However, it works well on Ubuntu 22.

BTW, the command "gpg --dearmor -o /etc/apt/keyrings/cri-o-apt-keyring.gpg" is not work on Ubuntu 20.
We should use "apt-key --keyring /etc/apt/trusted.gpg.d/kubernetes-apt-keyring.gpg add -" on Ubuntu 20.

**Comment by alanpeng** [comment]
curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key | gpg --dearmor -o /etc/apt/trusted.gpg.d/kubernetes-apt-keyring.gpg

**Comment by saschagrunert** [comment]
Does it work for the `prerelease` channels?

**Comment by alanpeng** [comment]
Same error in prerelease channels

**Comment by afbjorklund** [comment]
Note that the repository explicitly points out the key path, so you can't move it to the default directory...

**Comment by alanpeng** [comment]
@afbjorklund You are right. thank you. I forgot to create the folder. No problem with Ubuntu 20 and 22 now.

mkdir -p /etc/apt/keyrings/
curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /' | tee /etc/apt/sources.list.d/kubernetes.list
apt-get update
apt-get install cri-o

**Comment by alanpeng** [comment]
For now, I am using different repositories for podman and cri-o and kubelet/kubectl/kubeadm.

(1) CRI-O
mkdir -p /etc/apt/keyrings/
curl -fsSL https://pkgs.k8s.io/addons:/cri-o:/prerelease:/v1.28/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/cri-o-apt-keyring.gpg
echo 'deb [signed-by=/etc/apt/keyrings/cri-o-apt-keyring.gpg] https://pkgs.k8s.io/addons:/cri-o:/prerelease:/v1.28/deb/ /' | tee /etc/apt/sources.list.d/cri-o.list

(2) K8s components
mkdir -p /etc/apt/keyrings/
curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /' | tee /etc/apt/sources.list.d/kubernetes.list && \

(3) Podman
I have to use the old repositories for Podman:
https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/
see https://podman.io/docs/installation

Not a good experience.

**Comment by alanpeng** [comment]
What version of cri-o should I use for the latest K8s releases (v1.25.15 / 1.26.10 / 1.27.7)?
![image](https://github.com/cri-o/packaging/assets/3273357/bd7d47fa-4b68-4f24-9e28-2d79ec5d0cc0)

**Comment by afbjorklund** [comment]
> What version of cri-o should I use for the latest K8s releases

Use the old Kubic repo, as documented on https://cri-o.io/

https://build.opensuse.org/project/subprojects/devel:kubic:libcontainers

**Comment by alanpeng** [comment]
got it. thanks.

**Comment by afbjorklund** [comment]
The podman packages are a problem, they are "missing".

**Comment by afbjorklund** [comment]
Note: the podman static binaries were removed in 4.1.0, due to lack of support.

https://github.com/containers/podman/commit/346beec35a11393e9c59278d47b18de337c2b06f

So there are no static podman binaries available, for this cri-o project to package.

Only `podman-remote`

**Comment by saschagrunert** [comment]
Closing, feel free to reopen if there is anything left open.
