### ISSUE TITLE
Remove /etc/crio/crio.conf.d/01-crio-runc.conf

### ISSUE THREAD

**Issue by Jeansen** [cri-o/packaging#66]
When installing cri-o, a drop-in file for cri-o-runc is installed in `/etc/crio/crio.conf.d/01-crio-runc.conf`. It should be either up to an administrator to place the right file in this drop-in folder or it should be part of the cri-o-runc package (from the libcontainers repo).  But binding this package to the assumption of having another package installed isn't the proper way to do things ;-).

Tested with version 1.28 and 1.29.

**Comment by haircommander** [comment]
that works for me, WDYT @saschagrunert

**Comment by Jeansen** [comment]
Alternatively, we could also leave the file in place, but disable (comment out) its content.

**Comment by afbjorklund** [comment]
It is now hardcoding crun, rather than runc.

`/etc/crio/crio.conf.d/10-crun.conf`

**Comment by saschagrunert** [comment]
> It is now hardcoding crun, rather than runc.
> 
> `/etc/crio/crio.conf.d/10-crun.conf`

Yes, so are we all set?

**Comment by saschagrunert** [comment]
Assuming we're all set now
