### ISSUE TITLE
Workaround needed to install both podman and cri-o

### ISSUE THREAD

**Issue by afbjorklund** [cri-o/packaging#67]
The `/usr/bin/conmon` is replaced by a non-compatible version...

So any old one needs to be saved first, or podman stops working:

```
mv /usr/bin/conmon /usr/libexec/podman/
```

conmon: option parsing failed: Unknown option --network-backend

----

Example from Fedora 39:

```
$ /usr/libexec/podman/conmon --version
conmon version 2.1.8
commit: 
$ /usr/libexec/crio/conmon --version
conmon version 2.1.10
commit: 09bcded8e9c49cf1ff1fda403feac5a08f22535f-dirty
```

Podman Engine version 4.8.2

The crun version is the same.

**Comment by afbjorklund** [comment]
The best would probably be for Fedora to also call `install.podman`:

https://src.fedoraproject.org/rpms/conmon/blob/rawhide/f/conmon.spec

Currently it only installs the copy for crio, but **not** the one for podman.

```specfile
%{__make} PREFIX=%{buildroot}%{_prefix} install.bin install.crio
```

**Comment by saschagrunert** [comment]
Would using a dedicated `conmon-crio` binary shipped with our packages work? We're also planning to move to conmon-rs in the future, but we would end up with the same issue if Podman switches as well. 

cc @haircommander

**Comment by afbjorklund** [comment]
Most likely we would (eventually) need some static packaging of podman too, so that users can choose if they want to use their (more or less outdated) system versions of podman and cri-o or if they want to install the latest and greatest.

The main issue here arises from trying to mix and match packages between nix and rpm. I don't _think_ it would be a problem, if you stayed on the system Kubernetes version supported by Fedora (1.27.2), for your `crio` installation?
