### ISSUE TITLE
Packaging conflict between cri-o and containers-common

### ISSUE THREAD

**Issue by afbjorklund** [cri-o/packaging#68]
The file `/etc/containers/policy.json` exists in both packages, causing a package conflict.

This makes it "impossible" to install both `podman` and `cri-o`, because of the file conflict.

There is a similar problems with `/usr/bin/crun`, that conflicts with crun. And with the conmons:

* #67

----

The problems with overwriting global config like /etc/crictl.yaml and /etc/cni/net.d are documented elsewhere...

It is only a problem if you install multiple container runtimes, or if you plan on installing a different CNI from pods.

**Comment by saschagrunert** [comment]
This is a tricky one, not exactly sure how to address this properly yet.
