### ISSUE TITLE
No deb Release.key for stable:v1.29

### ISSUE THREAD

**Issue by TheNewJavaman** [cri-o/packaging#98]
prerelease:main has a deb signing key at [https://pkgs.k8s.io/addons:/cri-o:/prerelease:/main/deb/Release.key](https://pkgs.k8s.io/addons:/cri-o:/prerelease:/main/deb/Release.key), but its stable:v1.29 counterpart at [https://pkgs.k8s.io/addons:/cri-o:/stable:/v1.29/deb/Release.key](https://pkgs.k8s.io/addons:/cri-o:/stable:/v1.29/deb/Release.key) does not exist. Is this intentional? [https://build.opensuse.org/projects/isv:kubernetes:addons:cri-o:stable:v1.29/signing_keys](https://build.opensuse.org/projects/isv:kubernetes:addons:cri-o:stable:v1.29/signing_keys) lists a key, although I don't know if this is the same.

**Comment by TheNewJavaman** [comment]
I mistook v1.29 for v1.30, nevermind!

**Comment by saschagrunert** [comment]
@TheNewJavaman v1.30 has no successful build yet. I assume the key will be available once we released CRI-O v1.30.0.
